### ISSUE TITLE
LanguageTool 5.1 ignores random paragraphs

### ISSUE THREAD

**Issue by matzex** [matze-dd/Tex2txt#31]
When I use the python script of tex2txt in combination with shell.py and use LanguageTool in version 5.1 some random paragraphs are ignored and they do not appear in the html output anymore.
I use the following command:
`python3 shell.py --html --language de-DE chapter-4.tex > report-4test.html`

I have not found any pattern for this so I can't provide an example for this issue. With LanguageTool 4.7 it does work, so I don't know what the problem is. I would like to use 5.1 because there are some updates and more grammar rules included.

Thanks and regards
Matthias

**Comment by matze-dd** [comment]
Thank you for reporting this!

I see two possibilities to approach the reason of the problem.

1. If you specify option --context with a negative argument, do you then see all of the text in the HTML report? If yes, LanguageTool very probablty does not detect mistakes in the text parts not displayed before. If not, then please give a notice.
2. To be on the save side, you could additionally invoke
    `python3 tex2txt.py --lang de chapter-4.tex > chapter-4.plain`.
File chapter-4.plain then will contain all the plain text that is sent to LanguageTool by shell.py. Please give me a notice, if something is missing.

From my own experience with LanguageTool I can report that the newer versions sometimes report less problems, since refined rules are better in avoiding false positives.

A final question: Did you already consider switching to [YaLafi](https://github.com/matze-dd/YaLafi)? This is the successor of Tex2txt that is not devloped anymore. You then would write
```
python3 -m yalafi.shell --html --language de-DE chapter-4.tex > report-4test.html
```

**Comment by matzex** [comment]
Thank you very much for your fast and helpful answer!

1. Yes, with `--context -1` the file includes all missing paragraphs and identified also more problems than before.
2. Yes with the text2text.py command and plain text file all missing paragraphs are also included.

I completely missed the YaLafi successor and testet it shortly. Also with YaLafi (using the shell script and changed the path to LanguageTool 5.1) the paragraphs are missing. So it looks like this is unrelated to tex2txt and YaLafi, don't know what the problem here is exactly. I will test this with LanguageTool 5.0 to see if this has the same problem.

**Comment by matze-dd** [comment]
> Thank you very much for your fast and helpful answer!

You are welcome!

> Yes, with --context -1 the file includes all missing paragraphs and identified also more problems (in the previously missing paragraphs) than before.

This sounds like a severe bug. With the default value of '--context 2', the HTML report should include all text parts containing a message from LanguageTool, and this should not depend on the LanguageTool version. Could you please try to construct an example text that demonstrates the issue, if it persists?

(Possibly, this has been solved with `EDIT. Clarified Point 1 with the found problems from LanguageTool`?)

**Comment by matzex** [comment]
> (Possibly, this has been solved with `EDIT. Clarified Point 1 with the found problems from LanguageTool`?)

No, it has not solved. I just changed my point one and added the part in the brackets "(in the previously missing paragraphs)". With `--context -1` all paragraphs are shown and without they are not visible.

I will try to construct an example in the next days and add it to this issue.

**Comment by matze-dd** [comment]
@matzex, could you please give a notice whether the problem persists?

Thank you in advance!
